# Multiple Linear Regression (MLR) in PyTorch — Notebook Summary & Interpretation

This notebook demonstrates how to perform multiple linear regression using PyTorch, both manually and with built-in modules. Below is a summary and interpretation of the key steps and results.

---

## 1. **Manual Prediction with Custom Weights and Bias**

- **Weights and Bias:**  
  The notebook starts by manually setting weights (`w`) and bias (`b`) for a regression model with two input features.
- **Prediction Function:**  
  A custom `forward` function is defined to compute predictions using matrix multiplication (`torch.mm`) and bias addition.
- **Single Sample Prediction:**  
  For an input `x = [[1.0, 2.0]]`, the model computes the output using the manually set weights and bias.
- **Batch Prediction:**  
  The same function is used to predict outputs for a batch of samples, showing how the model generalizes to multiple inputs.

**Interpretation:**  
This section illustrates the mechanics of linear regression: predictions are made by multiplying inputs by weights and adding a bias. The results confirm the expected output for both single and multiple samples.

---

## 2. **Using PyTorch's Built-in Linear Layer**

- **Model Creation:**  
  A `nn.Linear` model is instantiated for two input features and one output.
- **Predictions:**  
  The model is used to predict outputs for both a single sample and a batch of samples.
- **Random Initialization:**  
  The weights and bias are randomly initialized, so predictions will differ from the manual case unless trained.

**Interpretation:**  
PyTorch's `nn.Linear` automates the weight and bias handling, making it easy to scale up to more complex models. The predictions at this stage are random, as the model has not been trained.

---

## 3. **Custom Linear Regression Class**

- **Class Definition:**  
  A custom `linear_regression` class is defined, inheriting from `nn.Module` and using an internal `nn.Linear` layer.
- **Parameter Inspection:**  
  The model's parameters (weights and bias) are printed both as a list and as a state dictionary.
- **Predictions:**  
  The custom model is used to predict outputs for both single and multiple samples.

**Interpretation:**  
Defining a custom class allows for more flexibility and extensibility, such as adding custom methods or additional layers. The predictions again reflect the random initialization of weights and bias.

---

## 4. **Practice: Predicting with a Larger Input Tensor**

- **Input Tensor:**  
  The model is tested on a larger input tensor `X = [[11, 12, 13, 14], [11, 12, 13, 14]]` using a custom linear regression class with four input features.
- **Prediction:**  
  The model outputs predictions for each row in the input tensor.

**Interpretation:**  
This demonstrates that the custom linear regression model can handle any input size as long as it matches the expected number of features. The predictions are again based on randomly initialized weights and bias.

---

## **Overall Summary**

- The notebook walks through manual and automated approaches to multiple linear regression in PyTorch.
- It shows how to set up weights and bias, define prediction functions, and use both built-in and custom model classes.
- Predictions before training are based on initial weights and bias, so they are not meaningful until the model is trained.
- The workflow provides a foundation for understanding and implementing linear regression for more complex datasets and models in PyTorch.

---
**Tip:**  
To obtain meaningful predictions, you would typically train the model using a loss function and an optimizer to adjust the weights and bias based on real data.

In [1]:
from torch import nn
import torch
torch.manual_seed(1)

# Prediction

In [2]:
# Set the weight and bias

w = torch.tensor([[2.0], [3.0]], requires_grad=True)  # Weight tensor for 2 input features, shape (2, 1)
b = torch.tensor([[1.0]], requires_grad=True)         # Bias tensor, shape (1, 1), requires gradient

# Define Prediction Function

def forward(x):
    yhat = torch.mm(x, w) + b  # Matrix multiply input x with weights w, then add bias b
    return yhat  # Return the predicted output

# Calculate yhat

x = torch.tensor([[1.0, 2.0]])  # Input sample with 2 features
yhat = forward(x)               # Compute prediction using the forward function
print("The result: ", yhat)     # Print the predicted output

The result:  tensor([[9.]], grad_fn=<AddBackward0>)


# Each Row in the Following Tensor will Represent a Sample

In [3]:
# Sample tensor X

X = torch.tensor([[1.0, 1.0],   # First sample: feature1=1.0, feature2=1.0
                  [1.0, 2.0],   # Second sample: feature1=1.0, feature2=2.0
                  [1.0, 3.0]])  # Third sample: feature1=1.0, feature2=3.0

# Make the prediction of X 

yhat = forward(X)  # Compute predictions for all samples in X using the forward function
print("The result: ", yhat)  # Print the predicted outputs for each sample

The result:  tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


# Class Linear

In [4]:
# Make a linear regression model using built-in function

model = nn.Linear(2, 1)  # Create a linear regression model with 2 input features and 1 output

# Make a prediction of x

yhat = model(x)  # Predict output for single sample x using the built-in model
print("The result: ", yhat)

# Make a prediction of X

yhat = model(X)  # Predict outputs for all samples in X using the built-in model
print("The result: ", yhat)

The result:  tensor([[-0.3969]], grad_fn=<AddmmBackward0>)
The result:  tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward0>)


# Building a Custom Model

In [5]:
# Create linear_regression Class

class linear_regression(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()  # Call parent class constructor
        self.linear = nn.Linear(input_size, output_size)  # Define linear layer
    
    # Prediction function
    def forward(self, x):
        yhat = self.linear(x)  # Forward pass through linear layer
        return yhat

model = linear_regression(2, 1)  # Instantiate the model with 2 input features and 1 output

In [6]:
# Print model parameters

print("The parameters: ", list(model.parameters()))  # List of Parameter objects (weights and bias)

# Print model parameters (state dict)

print("The parameters: ", model.state_dict())  # Dictionary of parameter names and tensors

# Make a prediction of x

yhat = model(x)  # Predict output for single sample x using the custom model
print("The result: ", yhat)

# Make a prediction of X

yhat = model(X)  # Predict outputs for all samples in X using the custom model
print("The result: ", yhat)

The parameters:  [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]
The parameters:  OrderedDict([('linear.weight', tensor([[ 0.3319, -0.6657]])), ('linear.bias', tensor([0.4241]))])
The result:  tensor([[-0.5754]], grad_fn=<AddmmBackward0>)
The result:  tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward0>)


In [7]:
# Building a model to predict the following tensor.
# X = torch.tensor([[11.0, 12.0, 13, 14], [11, 12, 13, 14]])

import torch
from torch import nn

# Define the input tensor X
X = torch.tensor([[11.0, 12.0, 13.0, 14.0],
                  [11.0, 12.0, 13.0, 14.0]])

# Define the custom linear regression class
class linear_regression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        return self.linear(x)

# Instantiate the model for 4 input features and 1 output
model = linear_regression(4, 1)

# Make predictions using the model
yhat = model(X)
print("Predicted values:\n", yhat)

Predicted values:
 tensor([[2.1062],
        [2.1062]], grad_fn=<AddmmBackward0>)
